// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_new_high_score_50000 = "CgkIhKeam-0IEAIQEg"; // <GPGSID>
        public const string achievement_new_high_score_10000 = "CgkIhKeam-0IEAIQEQ"; // <GPGSID>
        public const string leaderboard_time_mode_best_player = "CgkIhKeam-0IEAIQCg"; // <GPGSID>
        public const string leaderboard_best_scores = "CgkIhKeam-0IEAIQBg"; // <GPGSID>
        public const string achievement_new_high_score_500 = "CgkIhKeam-0IEAIQDg"; // <GPGSID>
        public const string leaderboard_score_mode_best_player = "CgkIhKeam-0IEAIQCw"; // <GPGSID>
        public const string achievement_level_medal = "CgkIhKeam-0IEAIQCQ"; // <GPGSID>
        public const string achievement_high_score_100 = "CgkIhKeam-0IEAIQDQ"; // <GPGSID>
        public const string achievement_new_high_score_1000 = "CgkIhKeam-0IEAIQDw"; // <GPGSID>
        public const string achievement_new_high_score_5000 = "CgkIhKeam-0IEAIQEA"; // <GPGSID>
        public const string leaderboard_level_mode_best_player = "CgkIhKeam-0IEAIQDA"; // <GPGSID>
        public const string achievement_score_medal = "CgkIhKeam-0IEAIQCA"; // <GPGSID>
        public const string achievement_time_medal = "CgkIhKeam-0IEAIQBw"; // <GPGSID>
        public const string achievement_new_high_score_100000 = "CgkIhKeam-0IEAIQEw"; // <GPGSID>

}

